services:
  master:
    build: .
    image: hadoop-spark-jdk21:latest
    container_name: master
    hostname: master
    environment:
      - NODE_TYPE=master
    ports:
      - "9870:9870" # HDFS NameNode Web UI
      - "8088:8088" # YARN Resource Manager Web UI
      - "8080:8080" # Spark Master Web UI
      - "19888:19888" # MapReduce JobHistory Web UI
      - "4040:4040" # Spark Application UI
    volumes:
      - master-hdfs-data:/opt/hadoop/data
      - ./config:/config-template # Giao diện chia sẻ cấu hình
    networks:
      - hadoop-net

  slave1:
    image: hadoop-spark-jdk21:latest
    container_name: slave1
    hostname: slave1
    environment:
      - NODE_TYPE=slave
    depends_on:
      - master
    ports:
      - "8081:8081" # Spark Worker 1 Web UI
    volumes:
      - slave1-hdfs-data:/opt/hadoop/data
    networks:
      - hadoop-net

  slave2:
    image: hadoop-spark-jdk21:latest
    container_name: slave2
    hostname: slave2
    environment:
      - NODE_TYPE=slave
    depends_on:
      - master
    ports:
      - "8082:8081" # Spark Worker 2 Web UI
    volumes:
      - slave2-hdfs-data:/opt/hadoop/data
    networks:
      - hadoop-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    networks:
      - hadoop-net

  superset:
    image: apache/superset:latest
    container_name: superset
    hostname: superset
    ports:
      - "8089:8088" # Port 8088 bị YARN chiếm nên map ra ngoài cổng 8089
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    volumes:
      - superset-data:/app/superset_home
    networks:
      - hadoop-net

volumes:
  superset-data:
  master-hdfs-data:
  slave1-hdfs-data:
  slave2-hdfs-data:

networks:
  hadoop-net:
    driver: bridge
